config/routes.rb
Rails.application.routes.draw do
  root "blog_posts#index"

  resources :blog_posts
end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  def index
    @blog_posts = BlogPost.all
  end

  def show
    @blog_post = BlogPost.find(params[:id])
  end

  def new
    @blog_post = BlogPost.new
  end

  def create
    blog_post = BlogPost.new(blog_post_params)
    blog_post.save

    redirect_to blog_posts_path
  end

  def edit
    @blog_post= BlogPost.find(params[:id])
  end

  def update
    @blog_post = BlogPost.find(params[:id])

    if @blog_post.update(blog_post_params)
      redirect_to blog_posts_path
    else
      render :edit
    end
  end

  def destroy
    blog_posts = BlogPost.find(params[:id])
    blog_posts.destroy
    redirect_to blog_posts_path
  end


  private

  def blog_post_params
    params.require(:blog_post).permit(:title, :author, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blog_posts/edit.html.erb
<h1> Edit Blog Post <h1>

<%= form_for @blog_post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>

  <%= f.label :author %>
  <%= f.text_field :author %>
  <br>

  <%= f.label :content %>
  <%= f.text_area :content %>
  <br>

  <%= f.submit "Update blog post!!!!!!" %>

<% end %>

app/views/blog_posts/index.html.erb
<% @blog_posts.each do |blog_post| %>
  <div>
    <p><%=  link_to blog_post.title, blog_post_path(blog_post) %></p>
  </div>
  <hr>
<% end %>

app/views/blog_posts/new.html.erb
<%= form_for BlogPost.new do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>

  <%= f.label :author %>
  <%= f.text_field :author %>
  <br>

  <%= f.label :content %>
  <%= f.text_area :content %>
  <br>

  <%= f.submit "Create blog post!!!!!!" %>

<% end %>

app/views/blog_posts/show.html.erb
<%= @blog_post.title %>

<br/>

<%= @blog_post.author %>

<br/>

<%= @blog_post.content %>

<br/>


<% link_to "New", new_blog_post_path %>
<%= link_to 'Edit', edit_blog_post_path(@blog_post) %>
<%= link_to 'Delete', blog_post_path(@blog_post), method: :delete, data: {confirm: "really? for rails?"} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogger</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>